### PR TITLE
Basic test added

### PR DESCRIPTION
**Pull request by gerardnico**
Hallo,

I got a unknown warning message on my template. I needed then to create a basic test to discover why I was getting it.
I found why (because of the `noscript` tag)

I have still created the test and if you want to add it to your repo, this PR is for you.

### CODE REVIEW

**Comment by gerardnico** [comment]
Still on vacation ?

**Comment by alexlehm** [comment]
@gerardnico sorry, i missed your post

**Review by alexlehm — APPROVED** [review]

**Comment by alexlehm** [comment]
@gerardnico  thanks i merged the pr now, can you please check if that works correctly?

it should be updates automatically by the plugin manager now

**Comment by gerardnico** [comment]
We use our own git project to be not external PR dependent. I can't test then now directly via the plugin manager.

The changes are minors, it should work ;)

Thanks.

**Pull request merged**
